apiVersion: skaffold/v4beta13
kind: Config
metadata:
  name: python-blockchain
build:
  artifacts:
    - image: backend
      context: .
      docker:
        dockerfile: backend/Dockerfile

    - image: frontend
      context: .
      docker:
        dockerfile: frontend/Dockerfile

    - image: backend-peer
      context: .
      docker:
        dockerfile: backend/Dockerfile
        
    - image: backend-seed
      context: .
      docker:
        dockerfile: backend/Dockerfile
manifests: # Watches + Applies changes to these files
  rawYaml:
    - k8s/*.yaml
    # - k8s/backend-deployment.yaml
    # - k8s/backend-peer-deployment.yaml
    # - k8s/backend-seed-deployment.yaml
    # - k8s/frontend-deployment.yaml
    # - k8s/nginx-gateway.yaml
    # - k8s/ingress.yaml
    # - k8s/hpa.yaml
    # - k8s/configMap.yaml

