apiVersion: skaffold/v4beta13
kind: Config
metadata:
  name: scaled-pychain
build:
  artifacts:
    - image: backend
      context: .
      docker:
        dockerfile: backend/Dockerfile

    - image: frontend
      context: .
      docker:
        dockerfile: frontend/Dockerfile

    - image: backend-peer
      context: .
      docker:
        dockerfile: backend/Dockerfile

    - image: backend-seed
      context: .
      docker:
        dockerfile: backend/Dockerfile
manifests: # Watches + Applies changes to these files
  rawYaml:
    - k8s/*.yaml
